packages:
  - frontend
  - docs

onlyBuiltDependencies:
  - "@parcel/watcher"
  - better-sqlite3
  - esbuild
  - unrs-resolver
  - vue-demi

patchedDependencies:
  vuetify@4.0.4: patches/vuetify@4.0.4.patch
